### ISSUE TITLE
Multiple definition of lock/unlock functions

### ISSUE THREAD

**Issue by stil4m** [mitchelkuijpers/TextShredder#1]
Different classes implement the lock/unlock functions:  
- EditList  
- ShadowCopy  
- WorkingCopy  

A 'Lockable' class should be created which implements these functions. All above classes should inherit from this class.

Things that should be done:
- Code  
- Class Diagram

**Comment by mitchelkuijpers** [comment]
The lockable class is useless because the QMutex class does exactly what we want. So the classes that we want to lock should just extend Qmutex.
