### ISSUE TITLE
Host multiple files on 1 server

### ISSUE THREAD

**Issue by stil4m** [mitchelkuijpers/TextShredder#20]
Currently a server is started with a file. 
This should be changed into 'starting without a file'.
When the server is started, the user can select which files he want to share.

When a client is connected, it should not do a download request directly, but should do a request for all available files. When all available files are received. The client can choose which file he wants to sync.

**Comment by stil4m** [comment]
When client connects make a request.

**Comment by mitchelkuijpers** [comment]
A client get's all currently syncable files without asking for it. This is because it would be useless to implement a packet that is only gonna be used once, and we know exactly when

**Comment by mitchelkuijpers** [comment]
It seems to work correctly :)
