### ISSUE TITLE
User should see if edits are processed

### ISSUE THREAD

**Issue by stil4m** [mitchelkuijpers/TextShredder#24]
When the user is editing a file. He should see when its edits are processed.
This should functionality should use the combination between the WorkingCopy and EditList

**Comment by wkonecny** [comment]
How to:

If EditList size has changed, send a signal. This could be two signals:
1. editListIsEmpty()
2. editListIsNotEmpty()

If editListIsNotEmpty(), place a "Not yet synced" icon in the file tree. Otherwise, just use the regular "Green" icon.

**Comment by stil4m** [comment]
Closed due end of project.
