### ISSUE TITLE
Performance test locking

### ISSUE THREAD

**Issue by stil4m** [mitchelkuijpers/TextShredder#40]
There should be a test for how long the lock occurs when synchronizing.
This should be done with small and big files.
Can be done with a unit test or an integration test.

**Comment by mitchelkuijpers** [comment]
This will be integrated in the ui. Later we are gonna build it so that you get a health indicator to see if youre server is performing well.

**Comment by wkonecny** [comment]
Added locking performance test in GUI

**Comment by wkonecny** [comment]
Opened again as the performance test will be extended.
