### ISSUE TITLE
backup/save server file

### ISSUE THREAD

**Issue by Corne** [mitchelkuijpers/TextShredder#48]
-save the current server file content when there are no longer syncthreads on the current file  
-back up all the server file contents every 5 minutes if it is syncing with clients

**Comment by mitchelkuijpers** [comment]
Why every 5 minutes and not every minute? or every 30 seconds? because 5 minutes loooks like a looooong time to me..

**Comment by wkonecny** [comment]
Yeah, saving isn't such a mind blowing operation. Saving every minute should be fine.
