### ISSUE TITLE
Clean up state emit from TSConnection

### ISSUE THREAD

**Issue by stil4m** [mitchelkuijpers/TextShredder#50]
The TSConnection state emit is a giant mess. Looks a little bit like Corne on the women toilet. UGH. Should be cleaned up for multiple reasons:
- User Interface should go to main menu if connection ended.
- Sync's must stop when socket is closed or receives an error. Otherwise the stack will be filled.

Currently there is a really crappy response to errors and socket closing. Should be looked at.

**Comment by wkonecny** [comment]
Quote from issue

> User Interface should go to main menu if connection ended.

What do you mean with that? Server side? Client side?
