### ISSUE TITLE
Design GUI

### ISSUE THREAD

**Issue by stil4m** [mitchelkuijpers/TextShredder#8]
The goal is to define a rich user interface as soon as possible.
There has to be thought about all components that will be put into the interface. The risk about <b>not</b> doing this is a GUI where all components are cropped in.
- List all features that have to put into the GUI.
- Make story board for the application.
- Review with whole group.
- Review with product owner (Alice).

**Comment by wkonecny** [comment]
The GUI has been designed and has been approved by Alice.
