### ISSUE TITLE
Update Class Commenting & Code Review

### ISSUE THREAD

**Issue by stil4m** [mitchelkuijpers/TextShredder#9]
A lot of files are lagged in commenting and need code review.

List all files current classes in this issue so they can be ticked off:

<table>
    <tr><th>File</th><th>Reviewed</th></tr>
    <tr><td>BackupCopy (2011/05/13 12:34) </td><td>NO</td></tr>
    <tr><td>Edit (2011/05/13 12:34) </td><td>NO</td></tr>
    <tr><td></td><td></td></tr>
    <tr><td></td><td></td></tr>

</table>

**Comment by maikdiepenbroek** [comment]
Almost done, after mats' refactoring this can be commented and closed
